version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=climberfish
      - POSTGRES_PASSWORD=climberfish
    ports:
      - 15432:5432
    volumes:
      - ./dkdata/postgres:/var/lib/postgresql/data

  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx_default_local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
